### ISSUE TITLE
Instance check for `JSON.parse` results

### ISSUE THREAD

**Issue by pheew** [tbknl/specified#1]
As this lib is also used for parsing `JSON.parse` the `Types.instance` check will always fail. How do you suggest to solve this? Currently I see 2 options:

- Use the `reviver` arg for `JSON.parse`. This kind of defeats the purpose of this lib
- Have the `Types.instance` check if it's actually convertable to the instance type in some way

**Comment by tbknl** [comment]
The purpose of `Type.instance` is to check if a value is an instance of the specified class, as in the following simplified example:
```typescript
class X {}
const xSpec = Type.instance(X);
const x = new X();
const result = verify(xSpec, x);
```

For data that comes out of `JSON.parse`, this type will not be very useful, as the only classes to check for would be `Object` or `Array`, for which better alternatives are available in `specified`.

An example of when it is useful would be when data comes from a (potentially untyped) third-party library.

Somewhere in future (when typescript is ready to support proper tuple types), `specified` will probably feature `Type.instantiate(ctor, paramsSpec)`, which will check first if the input value is according to the `paramsSpec` tuple before passing it as the arguments of the ctor, resulting in a new instance of its class.

This kind of data transformation however is something that I'm still unsure about whether it fits within the purpose of `specified`.

**Comment by pheew** [comment]
Ok thanks for the explanation. That makes sense actually 👍
