### ISSUE TITLE
Please add a verifyWithThrow() version that will throw the ValidationError if any

### ISSUE THREAD

**Issue by mattbishop** [tbknl/specified#5]
Oftentimes I want my spec to throw an error if the verification fails. Right now I have to check the result of verify() and throw myself if it's an error. This is tedious. For instance:

```typescript
const {err} = verify(aSpec, aValue)
if (err) {
  throw err
}
```

An alternate method, or perhaps a verify option, would make this use case easier.

**Comment by tbknl** [comment]
Hi @mattbishop , the `value()` function on the verification-result already does throws the err in case there is one.
In my own code I often write
```ts
const value = verify(aSpec, aValue).value()
```
which has the exact same behavior as your code snippet.

**Comment by tbknl** [comment]
I see now that it is missing from the readme that the `value()` function throws in case of an error. This behavior has been there since the first version. I'll add it soon to the documentation.

**Comment by mattbishop** [comment]
Yes that makes sense. I can do this too.

**Comment by tbknl** [comment]
Closing this issue, as a solution is provided.
