### ISSUE TITLE
Type.function spec to test for a function type

### ISSUE THREAD

**Issue by mattbishop** [tbknl/specified#7]
I have an object (command handler) that has some properties that are functions, not data. I can't find a way to verify that the members are functions instead of data. For instance:

```js
const handler = {
  process: (data) => doSomething(data)
}
```

I want a way to spec the `process` member to be a function.

**Comment by mattbishop** [comment]
@tbknl would you consider a PR for this issue?

**Comment by tbknl** [comment]
@mattbishop I recommend to use `specified` to validate and type outside data as soon as it enters the program, or just before it leaves the program. In these cases the data should not contain functions, as function objects itself can't be communicated across program boundaries.

I'm curious your use case for `specified`, as I can't imagine a use case myself in which you would want to use it to validate objects that may contain functions.

**Comment by tbknl** [comment]
On a side-note, I'm very close now to finishing version 1.0.0 of `specified`. It contains documentation on how you can define your own custom types and constraints. If you really need it, you can use that to create a 'function' custom type.

**Comment by mattbishop** [comment]
That's great to hear!

I am migrating an app that currently uses js.spec to specified (https://www.npmjs.com/package/js.spec) and I am using the `function` spec to validate a user-constructed object has a particular function defined. It's a CQRS library that can take user-defined command handler objects, so I am using spec to validate their command handler meets the basic criteria of the command handler. It's not deserialized data, but dynamically-registered strategies.

**Comment by tbknl** [comment]
If you don't want to wait for the new version of specified, you can also make your own custom type right now already, although the interface is not official yet. Just copy one of the simple types from `src/type.ts` such as `Type.string` and modify it to check for a function:
```typescript
const Type_function = {
    definition: {
        type: "function"
    },
    eval: (value: unknown) => {
        if (typeof value !== "function") {
            throw new ValidationError("Not a function.");
        }
        return value;
    }
};
```

**Comment by tbknl** [comment]
That's an interesting use case of specified by the way. I've never had such a use case in mind. But now that I know about it, I will keep it in mind for future directions of this package.

**Comment by mattbishop** [comment]
Thanks for the suggestion, I can make that work for my use case.

**Comment by tbknl** [comment]
Closing this issue, as the provided solution is accepted.
